name: Generate APK

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Gradle and Generate Wrapper
        run: |
          sudo apt-get update && sudo apt-get install -y gradle
          gradle wrapper

      - name: Commit and Push Wrapper Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add gradlew gradlew.bat gradle/wrapper/
          git commit -m "chore: auto-generate gradle wrapper"
          git push origin staging
