name: Generate APK

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Set the working directory to the 'android' folder for all run steps
    defaults:
      run:
        working-directory: ./android

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full history is fetched for submodule references

      - name: Force Sync and Update Submodules
        # We run this from the root directory to capture the top-level .gitmodules
        working-directory: ./
        run: |
          git submodule deinit -f . || true
          git submodule sync --recursive
          git submodule update --init --recursive --force --prune

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.BASE64_KEYSTORE }}" | base64 --decode > keystore.jks

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "storeFile=${{ secrets.STORE_FILE }}" >> local.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> local.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> local.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> local.properties

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build APK for Staging
        run: ./gradlew :app:assembleRelease_stripped

      - name: Debug - Find APK files
        run: find app/build/outputs/apk -name "*.apk" -type f

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Gameskii-staging-apk
          path: android/app/build/outputs/apk/**/*.apk
